Need to specify pypy3 explicitly: pypy3.11.
Otherwise `actions/setup-python` says:

```
Error: Invalid format of Python version for PyPy.
Python version should be specified in format 'x.y'.
See README for examples and documentation.
```